export * from './enums';
export * from './types';
export * from './models';
export * from './utils';
export * from './errors';
export * from './versioning';
export * from './diff';
export * from './services';
export * from './repositories';
export * from './policy';
export {
  // Re-export solver types with explicit names to avoid conflicts with ./types
  solve,
  buildSolverInput,
  evaluateCandidatePolicies,
  NoOpAvailabilityProvider,
  buildModel,
  solveDeterministic,
  extractCandidate,
  computeStabilityScore,
  computeFamilyStructureScore,
  computeFairnessScore,
  computeParentPreferenceScore,
  computeChildPreferenceScore,
  computeLogisticsScore,
  computeConvenienceScore,
  computeCandidateScore,
  rankCandidates,
  deduplicateCandidates,
  buildArtifacts,
  SolverInputValidationError,
  SolverModelBuildError,
  SolverNoFeasibleSolutionError,
  SolverCandidateExtractionError,
  SolverRankingError,
} from './solver';
export type {
  PlanningWindow,
  SolverInput,
  SolverConfig,
  ObjectiveWeights,
  FairnessState,
  FixedHolidayAssignment,
  DayInfo,
  NormalizedSolverInput,
  CandidateNight,
  CandidateExchange,
  SolverScore,
  SolverCandidateMetadata,
  SolverCandidate,
  SolverArtifact,
  SolverResult,
  AssignmentVariable,
  BuiltScheduleModel,
  UnavailableAssignment,
  AvailabilityConstraintProvider,
  WeightProfile,
} from './solver';
// SolverScoreBreakdown conflicts with types/index.ts — use solver's version via solver import
export {
  solveRepairProblem,
  buildRepairInput,
  buildRepairWindow,
  evaluateRepairPolicies,
  validateOverlays,
  normalizeOverlays,
  applyOverlays,
  calculateOverlayDrift,
  identifyRestitutionTargets,
  driftToLedgerUpdates,
  buildRepairModel,
  solveRepair,
  extractRepairCandidate,
  computeRepairStabilityScore,
  computeRepairFamilyStructureScore,
  computeFairnessRestitutionScore,
  computeNearTermCalmnessScore,
  computeRepairScore,
  rankRepairCandidates,
  deduplicateRepairCandidates,
  buildRepairArtifacts,
  RepairInputValidationError,
  OverlayValidationError,
  OverlayConflictError,
  RepairWindowError,
  RepairModelBuildError,
  RepairNoFeasibleSolutionError,
  RepairCandidateExtractionError,
  RepairRankingError,
} from './repair';
export type {
  RepairWindow,
  DisruptionOverlaySnapshot,
  AppliedOverlayResult,
  OverlayImpact,
  FairnessDriftSummary,
  RestitutionTarget,
  RepairInput,
  RepairSolverConfig,
  RepairObjectiveWeights,
  RepairScore,
  RepairScoreBreakdown,
  RepairCandidate,
  RepairArtifact,
  RepairResult,
} from './repair';
// Fairness (Phase 6)
export {
  FairnessEventType,
  FairnessValidationError,
  FairnessLedgerNotFoundError,
  FairnessDuplicateEventError,
  FairnessProjectionError,
  FairnessReconciliationError,
  fromOverlayDrift,
  fromRepairRestitution,
  fromProposalAcceptanceReconciliation,
  fromManualAdjustment,
  applyDeltaBatch,
  reconcileAcceptedScheduleChange,
  buildLedgerState,
  createEmptyLedgerState,
  buildFairnessArtifacts,
  calculateScheduleDelta,
  projectFairness,
  FairnessStateService,
  driftSummaryToDeltaBatch,
  ledgerStateToSolverFairnessState,
  solverFairnessStateToLedgerState,
  buildIdempotencyKey,
} from './fairness';
export type {
  FairnessLedgerState,
  FairnessLedgerRow,
  FairnessLedgerEventRecord,
  FairnessDelta,
  FairnessDeltaBatch,
  FairnessProjectionInput,
  FairnessProjectionResult,
  FairnessArtifact,
  FairnessStateServiceDeps,
  IFairnessLedgerRepository,
  FairnessLedgerUpsertInput,
  IFairnessLedgerEventRepository,
} from './fairness';
// Proposals (Phase 7)
export {
  ProposalGenerationError,
  ProposalReviewError,
  ProposalAcceptanceError,
  ProposalRejectionError,
  ProposalInvalidationError,
  ProposalOriginError,
  ProposalArtifactError,
  ProposalGenerationService,
  materializeCandidate,
  ProposalFairnessCoordinator,
  ProposalOverlayCoordinator,
  collectCandidateArtifacts,
  ProposalReviewService,
  buildScoreSummary,
  buildFairnessSummary,
  ProposalAcceptanceWorkflow,
  ProposalRejectionWorkflow,
  ProposalInvalidationService,
  buildDiffArtifact,
  buildChangedNightArtifact,
  buildExchangeArtifact,
  buildScoreArtifact,
  buildFairnessArtifact,
  buildAcceptanceArtifact,
  buildReviewArtifacts,
} from './proposals';
export type {
  ProposalOrigin,
  ProposalGenerationInput,
  ProposalCandidateInput,
  ProposalReviewBundle,
  ProposalScoreSummary,
  ProposalFairnessSummary,
  ProposalReviewMetadata,
  ProposalArtifact,
  ProposalAcceptanceInput,
  ProposalAcceptanceResult,
  ProposalReviewServiceDeps,
  ProposalAcceptanceWorkflowDeps,
  IDisruptionOverlayRepository,
} from './proposals';
// Messaging (Phase 8)
export {
  IntentType,
  IntentExtractionError,
  IntentValidationError,
  IntentResolutionError,
  MessageInterpretationError,
  IntentRoutingError,
  AmbiguousIntentError,
  UnsupportedIntentTypeError,
  IntentSchemaRegistry,
  IntentCandidateValidator,
  MessageInterpretationValidator,
  getSchemaForIntentType,
  getAllIntentTypes,
  availabilityChangePayloadSchema,
  swapRequestPayloadSchema,
  disruptionReportPayloadSchema,
  proposalRequestPayloadSchema,
  policyConfirmationPayloadSchema,
  LlmIntentExtractionProvider,
  MockIntentExtractionProvider,
  createStandardMockProvider,
  buildIntentExtractionPrompt,
  EntityReferenceResolver,
  DateReferenceResolver,
  IntentResolutionCoordinator,
  MessageInterpretationService,
  MessageInterpretationPersistence,
  IntentRouter,
  AvailabilityChangeRoute,
  SwapRequestRoute,
  DisruptionReportRoute,
  ProposalRequestRoute,
  PolicyConfirmationRoute,
} from './messaging';
export type {
  IncomingMessage,
  ExtractedIntentCandidate,
  IntentExtractionResponse,
  ExtractionFamilyContext,
  ValidatedIntentCandidate,
  InterpretedIntent,
  ResolvedEntityMap,
  InterpretationFailure,
  InterpretationStatus,
  MessageInterpretationResult,
  WorkflowRouteResult,
  EntityResolutionResult,
  DateResolutionResult,
  AvailabilityChangePayload,
  SwapRequestPayload,
  DisruptionReportPayload,
  ProposalRequestPayload,
  PolicyConfirmationPayload,
  IntentRecord,
  IntentExtractionProvider,
  LlmClient,
  CandidateValidationResult,
  InterpretationValidationResult,
  MessageInterpretationServiceDeps,
  FamilyContextLoader,
  IntentRoute,
  IIntentRepository,
} from './messaging';
// Calendar (Phase 9)
export {
  CalendarNormalizationError,
  CalendarScopeResolutionError,
  CalendarClassificationError,
  CalendarIngestionError,
  CalendarTranslationError,
  CalendarDeduplicationError,
  CalendarScopeResolver,
  CalendarSolverAdapter,
  CalendarEventKindInferer,
  CalendarConstraintClassifier,
  getClassificationRule,
  CalendarEventNormalizer,
  CalendarEventDeduplicator,
  CalendarEventIngestionService,
  CalendarConstraintTranslator,
  CalendarAvailabilityBuilder,
  CalendarProjectionService,
  buildIngestionArtifact,
  buildClassificationArtifact,
  buildWindowConstraintArtifact,
  buildUnresolvedScopeArtifact,
  materializeToRecord,
  materializeBatch,
} from './calendar';
export type {
  CalendarEventScopeType,
  CalendarEventKind,
  CalendarConstraintLevel,
  ExternalCalendarEvent,
  NormalizedCalendarEvent,
  ClassifiedCalendarEvent,
  CalendarConstraintRecord,
  CalendarAvailabilityView,
  CalendarTranslationResult,
  CalendarArtifact,
  CalendarProjectionInput,
  CalendarFamilyContext,
  CalendarIngestionResult,
  CalendarEventRecord,
  ScopeResolutionResult,
  DeduplicationResult,
  CalendarEventIngestionServiceDeps,
  ICalendarEventRepository,
} from './calendar';
// Explanations (Phase 10)
export {
  ExplanationBuildError,
  ExplanationQueryError,
  ExplanationPersistenceError,
  ExplanationArtifactNormalizationError,
  UnsupportedExplanationTargetError,
  ArtifactNormalizer,
  SourceArtifactRegistry,
  ExplanationEngine,
  ChangeExplanationBuilder,
  FairnessExplanationBuilder,
  PolicyExplanationBuilder,
  CalendarExplanationBuilder,
  AcceptanceExplanationBuilder,
  ExplanationSummaryBuilder,
  ExplanationQueryService,
  ExplanationBundleAssembler,
} from './explanations';
export type {
  ExplanationTargetType,
  ExplanationImportance,
  ExplanationCategory,
  SourceArtifactRef,
  ExplanationRecord,
  ExplanationSummary,
  ExplanationArtifact,
  ExplanationBundle,
  NormalizedArtifact,
  ScheduleSnapshot,
  ChangeExplanationInput,
  ExplanationBuildInput,
  ExplanationQueryResult,
  IExplanationRecordRepository,
  IExplanationSourceArtifactRepository,
  RawArtifactInput,
  ExplanationEngineDeps,
  ExplanationQueryServiceDeps,
} from './explanations';
// Scenarios (Phase 11)
export {
  ScenarioFixtureValidationError,
  ScenarioSeedError,
  ScenarioExecutionError,
  ScenarioAssertionError,
  ScenarioDeterminismError,
  ScenarioGoldenMismatchError,
  ScenarioSeeder,
  ScenarioNameResolver,
  ScenarioFixtureLoader,
  ScenarioFixtureValidator,
  BUILTIN_FIXTURES,
  ScenarioRunner,
  ScenarioStepExecutor,
  ScenarioAssertionEngine,
  ScenarioExpectationEvaluator,
  DeterminismAssertionRunner,
  ScenarioCanonicalizer,
  ScenarioGoldenSerializer,
  ScenarioReportBuilder,
} from './scenarios';
export type {
  ScenarioFixture,
  ScenarioSeed,
  ScenarioStep,
  ScenarioSolveBaselineStep,
  ScenarioApplyOverlayStep,
  ScenarioRunRepairStep,
  ScenarioGenerateProposalsStep,
  ScenarioAcceptProposalStep,
  ScenarioRejectProposalStep,
  ScenarioIngestCalendarStep,
  ScenarioAppendFairnessAdjustmentStep,
  ScenarioBuildExplanationStep,
  ScenarioExpectation,
  ActiveScheduleExpectation,
  ProposalCountExpectation,
  FairnessLedgerExpectation,
  OverlayResolutionExpectation,
  PolicyExpectation,
  CalendarClassificationExpectation,
  ExplanationExpectation,
  DeterminismExpectation,
  ScenarioStepResult,
  ScenarioAssertionResult,
  ScenarioReport,
  ScenarioExecutionResult,
  SeededScenarioContext,
  ScenarioExecutionContext,
} from './scenarios';
// Simulation (Phase 12)
export {
  SimulationFixtureValidationError,
  SimulationExecutionError,
  SimulationMetricError,
  SimulationDeterminismError,
  SimulationGoldenMismatchError,
  SimulationClock,
  SimulationStepExecutor as SimStepExecutor,
  SimulationRunner,
  DeterministicEventSampler,
  SimulationEventPolicyEngine,
  SimulationEventGenerator,
  SimulationPersonaRegistry,
  StructuredCoParentPersona,
  HighConflictPersona,
  LogisticsHeavyPersona,
  FlexibleCoParentPersona,
  SimulationMetricCollector,
  SimulationAggregateMetricBuilder,
  computeScheduleChurnRate,
  computeAverageTransitionCount,
  computeFairnessDeviationMagnitude,
  computeSiblingDivergenceRate,
  computeDisruptionRecoveryOpenCount,
  computePendingProposalCount,
  SimulationAssertionEngine,
  SimulationDeterminismRunner,
  SimulationCanonicalizer,
  SimulationReportBuilder as SimReportBuilder,
  SimulationGoldenSerializer,
} from './simulation';
export type {
  SimulationFixture,
  SimulationConfig,
  SimulationPersonaType,
  SimulationPersonaAssignment,
  SimulationEventPolicy,
  SimulationStep,
  SimulationOverlayEvent,
  SimulationSwapIntentEvent,
  SimulationCalendarImportEvent,
  SimulationFairnessAdjustmentEvent,
  SimulationGeneratedEvent,
  SimulationMetricSnapshot,
  SimulationAggregateMetrics,
  SimulationDeterminismExpectation,
  SimulationMetricBoundExpectation,
  SimulationFairnessConvergenceExpectation,
  SimulationCalmnessExpectation,
  SimulationExpectation,
  SimulationStepResult,
  SimulationAssertionResult,
  SimulationReport,
  SimulationExecutionResult,
  SimulationFamilyContext,
  SimulationExecutionContext,
  SimulationPersona,
} from './simulation';
// Observations (Phase 13)
export {
  ObservationEvidenceError,
  PatternDetectionError,
  PolicySuggestionError,
  PolicySuggestionResolutionError,
  PolicySuggestionReviewError,
  UnsupportedSuggestionConversionError,
  AcceptedProposalEvidenceExtractor,
  ExchangePatternEvidenceExtractor,
  OverlayCoverageEvidenceExtractor,
  ActivityResponsibilityEvidenceExtractor,
  PreferredExchangeDayDetector,
  PreferredExchangeLocationDetector,
  SchoolClosureCoverageDetector,
  MinBlockLengthAdjustmentDetector,
  ActivityResponsibilityDetector,
  SiblingDivergencePreferenceDetector,
  PatternDetectorRegistry,
  PolicySuggestionService,
  SuggestionDeduplicator,
  SuggestionEvidenceSummarizer,
  PolicySuggestionReviewService,
  PolicySuggestionArtifactBuilder,
  PolicySuggestionResolutionWorkflow,
} from './observations';
export type {
  BehaviorObservationWindow,
  ObservationEvidenceRecord,
  PolicySuggestionType,
  PolicySuggestionStatus,
  SuggestionEvidenceSummary,
  PolicySuggestion,
  PolicySuggestionCandidate,
  PolicySuggestionReviewBundle,
  SuggestionResolutionInput,
  SuggestionResolutionResult,
  PolicySuggestionEvidenceLink,
  ObservationEvidenceExtractor,
  PatternDetector,
  AcceptedProposalRecord,
  ExchangeRecord,
  OverlayCoverageRecord,
  ActivityRecord,
  PolicySuggestionServiceDeps,
  PolicySuggestionReviewServiceDeps,
  PolicySuggestionResolutionWorkflowDeps,
  IObservationEvidenceRepository,
  IPolicySuggestionRepository,
  IPolicySuggestionEvidenceLinkRepository,
} from './observations';
