import { DisruptionEventType } from '@adcp/shared';
import type { ScenarioPreset } from '../../stores/scenario';

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'balanced',
    name: 'Balanced Co-Parenting',
    category: 'Common',
    description: 'Standard 50/50 shared custody, two school-age children, close proximity.',
    family: {
      childCount: 2,
      childAges: [6, 10],
      distanceMiles: 12,
      targetSplit: 50,
      schoolAnchor: 'Elementary School',
      exchangeLocation: 'At School',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 7,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'alternating',
      fairnessBand: 5,
    },
    disruptions: [],
  },
  {
    id: 'long-distance',
    name: 'Long Distance Parents',
    category: 'Common',
    description: 'Parents 45 minutes apart. Fewer transitions, longer blocks.',
    family: {
      childCount: 1,
      childAges: [8],
      distanceMiles: 45,
      targetSplit: 50,
      schoolAnchor: 'Elementary School',
      exchangeLocation: 'Midpoint',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 14,
      minConsecutive: 3,
      maxTransitionsPerWeek: 2,
      weekendSplit: 'alternating',
      fairnessBand: 8,
    },
    disruptions: [],
  },
  {
    id: 'shift-work',
    name: 'Shift Work Parent',
    category: 'Common',
    description: 'Parent A works rotating shifts. Irregular availability.',
    family: {
      childCount: 1,
      childAges: [5],
      distanceMiles: 20,
      targetSplit: 40,
      schoolAnchor: 'Daycare',
      exchangeLocation: 'At Daycare',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: { '1': 'parent_b', '3': 'parent_b' },
      maxConsecutive: 5,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'split',
      fairnessBand: 10,
    },
    disruptions: [],
  },
  {
    id: 'three-kids-mixed',
    name: 'Three Children Mixed Ages',
    category: 'Complex',
    description: 'Toddler, school-age, and teen. Very different needs.',
    family: {
      childCount: 3,
      childAges: [3, 8, 15],
      distanceMiles: 25,
      targetSplit: 50,
      schoolAnchor: 'School',
      exchangeLocation: 'At School',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 5,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'alternating',
      fairnessBand: 5,
    },
    disruptions: [],
  },
  {
    id: 'frequent-travel',
    name: 'Frequent Travel Parent',
    category: 'Complex',
    description: 'Parent A travels 3 weeks per month. Tests coverage requests.',
    family: {
      childCount: 2,
      childAges: [7, 11],
      distanceMiles: 15,
      targetSplit: 50,
      schoolAnchor: 'School',
      exchangeLocation: 'At School',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 10,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'alternating',
      fairnessBand: 8,
    },
    disruptions: [
      {
        id: 'travel-1',
        type: DisruptionEventType.PARENT_TRAVEL,
        startDate: '2026-03-16',
        endDate: '2026-03-20',
        affectedParent: 'parent_a',
        description: 'Business trip week 1',
      },
      {
        id: 'travel-2',
        type: DisruptionEventType.PARENT_TRAVEL,
        startDate: '2026-03-30',
        endDate: '2026-04-03',
        affectedParent: 'parent_a',
        description: 'Business trip week 2',
      },
    ],
  },
  {
    id: 'holiday-conflict',
    name: 'Holiday Conflict',
    category: 'Disruptions',
    description: 'Thanksgiving + school closure week. Tests holiday overlay.',
    family: {
      childCount: 2,
      childAges: [6, 9],
      distanceMiles: 18,
      targetSplit: 50,
      schoolAnchor: 'School',
      exchangeLocation: 'At School',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 7,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'alternating',
      fairnessBand: 5,
    },
    disruptions: [
      {
        id: 'thanksgiving',
        type: DisruptionEventType.PUBLIC_HOLIDAY,
        startDate: '2026-11-26',
        endDate: '2026-11-26',
        description: 'Thanksgiving Day',
      },
      {
        id: 'thanksgiving-break',
        type: DisruptionEventType.BREAK,
        startDate: '2026-11-23',
        endDate: '2026-11-27',
        description: 'Thanksgiving Break',
      },
    ],
  },
  {
    id: 'school-closure-week',
    name: 'School Closure Week',
    category: 'Disruptions',
    description: 'Full week school closure + weather emergency.',
    family: {
      childCount: 1,
      childAges: [7],
      distanceMiles: 15,
      targetSplit: 50,
      schoolAnchor: 'School',
      exchangeLocation: 'At School',
      arrangement: 'shared',
    },
    constraints: {
      lockedNights: {},
      maxConsecutive: 7,
      minConsecutive: 2,
      maxTransitionsPerWeek: 3,
      weekendSplit: 'alternating',
      fairnessBand: 5,
    },
    disruptions: [
      {
        id: 'snow-1',
        type: DisruptionEventType.WEATHER_EMERGENCY,
        startDate: '2026-03-09',
        endDate: '2026-03-09',
        description: 'Snow day Monday',
      },
      {
        id: 'closure-week',
        type: DisruptionEventType.SCHOOL_CLOSED,
        startDate: '2026-03-10',
        endDate: '2026-03-13',
        description: 'School closed (pipes burst)',
      },
    ],
  },
];

export const SCENARIO_CATEGORIES = [...new Set(SCENARIO_PRESETS.map((p) => p.category))];
