export enum IntentType {
  AVAILABILITY_CHANGE = 'AVAILABILITY_CHANGE',
  SWAP_REQUEST = 'SWAP_REQUEST',
  DISRUPTION_REPORT = 'DISRUPTION_REPORT',
  PROPOSAL_REQUEST = 'PROPOSAL_REQUEST',
  POLICY_CONFIRMATION = 'POLICY_CONFIRMATION',
}
